name: Run PyTest

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['dev']
  push:
    branches: ['main']

jobs:
  test-and-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4.1
      with:
        python-version: ${{ matrix.python-version }}
        python-path: ${{ runner.tool_cache }}/Python/${{ matrix.python-version }}/x64

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Install dependencies
      run: |
        pdm install --prod --frozen-lockfile --no-editable
        pip install --upgrade pip
        pip install flake8 pytest

    - name: Run Tests
      run: |
        source $(pdm venv activate)
        pdm run -v pytest tests

    - name: Lint with flake8
      run: |
        source $(pdm venv activate)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Cache PDM packages
      uses: actions/cache@v3
      with:
        path: ~/.pdm/cache
        key: ${{ runner.os }}-pdm-${{ hashFiles('pdm.lock') }}
        restore-keys: |
          ${{ runner.os }}-pdm-
